server:
  shutdown: graceful
  port: 8081

spring:
  application:
    name: gateway-service
  profiles:
    active: dev

logging:
  level:
    org:
      springframework: DEBUG
      reactor.netty.http.client: DEBUG