server:
  shutdown: graceful
  port: 8081

jwt:
  secret:
    key: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArYUG637BzBWrUNLb3MKPYnvFuqTp3/akNn2NALDxh0TUU5zlBxSJSjsDQuEqRfYdvmizOyzbKGNhLpM5cxuZFp8KTQvTQKF7aymoy4Z8sSzzKABSOqYfloSANV1j64uv4e3NSUxUcd0B/ermTKS2kq1RWLuEnVuPKAzRN9FfVZNTgMfGSWsRvzymL6bOeqa1/hqIyjr+euyFnHabMOj4FZSp90omM96mNMgvsnYK6lC/c/AgPeDSYaoOyzvRbu7t98+XvJt3SkVHohtMVHz/8RMzsuqwInp5JvV81xXYI+ju/KJTLsDv3f8mUCg9j/G3nFkHAB+mHLl/kyi71A5glwIDAQAB-----END PUBLIC KEY-----

spring:
  cloud:
    gateway:
      routes:
        - id: product-service-public
          predicates:
            - Path=/public/**
          uri: http://localhost:8080
          filters:
            - RewritePath=/public/(?<segment>.*), /${segment}

        #        - id: product-service-protected
        #          predicates:
        #            - Path=/product/**
        #            - Method=POST
        #          uri: http://localhost:8080
        #          filters:
        #            - RewritePath=/product/(?<segment>.*), /${segment}
        #            - name: JwtAuthenticationFilter
        #              args:
        #                secretKey: ${jwt.secret.key}

        - id: product-service-with-authentication
          predicates:
            - Path=/product/**
          uri: http://localhost:8080
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
            - name: JwtAuthenticationFilter
              args:
                secretKey: ${jwt.secret.key}

        - id: member-service-with-authentication
          predicates:
            - Path=/member/**
          uri: http://localhost:8080
          filters:
            - RewritePath=/member/(?<segment>.*), /$\{segment}
            - name: JwtAuthenticationFilter
              args:
                secretKey: ${jwt.secret.key}

        - id: token-service
          predicates:
            - Path=/token/**
          uri: http://localhost:8082
          filters:
            - RewritePath=/token/(?<segment>.*), /$\{segment}
