spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            predicates:
              - Path=/**
            uri: http://product-service:8090
            filters:
              - RewritePath=/auth/(?<segment>.*), /$\{segment}