server:
  shutdown: graceful
  port: 8081

spring:
  application:
    name: gateway-service
  profiles:
    include:
      - route
    active: dev

logging:
  level:
    org:
      springframework: DEBUG